export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_EXISTS: "AUTH_USER_EXISTS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FORMAT: "INVALID_FORMAT",
  PROCESSING_ERROR: "PROCESSING_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  VIDEO_NOT_READY: "VIDEO_NOT_READY",
  STORAGE_ERROR: "STORAGE_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ErrorResponse = {
  statusCode: number;
  code: ErrorCode;
  message: string;
  details?: Record<string, string[]>;
};
